[package]
name = "orange-sdk"
version = "0.1.0"
edition = "2024"

[features]
_test-utils = ["corepc-node"]

[dependencies]
graduated-rebalancer = { path = "../graduated-rebalancer", version = "0.1.0" }

ldk-node = { git = "https://github.com/benthecarman/ldk-node.git", branch = "esplora-auth" }
bitcoin-payment-instructions = { version = "0.4.0", features = ["http"] }
chrono = { version = "0.4", default-features = false }
rand = "0.8.5"
reqwest = { version = "0.12.23", default-features = false, features = ["rustls-tls"] }
spark-wallet = { path = "../../rust-spark/crates/spark-wallet" }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "sync"] }
uuid = { version = "1.0", default-features = false }

corepc-node = { version = "0.8.0", features = ["29_0", "download"], optional = true }
