[package]
name = "orange-sdk"
version = "0.1.0"
edition = "2024"

[features]
_test-utils = ["corepc-node"]

[dependencies]
ldk-node = { git = "https://github.com/benthecarman/ldk-node.git", branch = "on-chain-fee-estimation" }
bitcoin-payment-instructions = { version = "0.4.0", features = ["http"] }
chrono = { version = "0.4", default-features = false }
rand = "0.8.5"
spark-rust = { version = "0.1.11" }
spark-protos = { version = "=0.1.9", default-features = false }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "sync"] }
uuid = { version = "1.0", default-features = false }

corepc-node = { version = "0.8.0", features = ["29_0", "download"], optional = true }

[dev-dependencies]
rustls = "0.23.26"
