[package]
name = "orange-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
ldk-node = { version = "0.5.0" }
bitcoin-payment-instructions = { version = "0.4.0", features = ["http"] }
chrono = { version = "0.4", default-features = false }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "sync"] }
spark-rust = { version = "0.1.11" }
spark-protos = { version = "=0.1.9", default-features = false }
uuid = { version = "1.0", default-features = false }

[dev-dependencies]
corepc-node = { version = "0.7.0", features = ["28_0", "download"] }
rand = "0.8.5"
rustls = "0.23.26"
